[tool.poetry]
name = "entity-resolution-project"
version = "0.1.0"
description = "A project for entity resolution using Siamese Neural Networks (SNN) with TensorFlow."
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.2.4"
numpy = "^1.20.3"
geopy = "^2.2.0"
openpyxl = "^3.0.7"
tabulate = "^0.8.9"
python-dotenv = "^0.19.1"
tensorflow = "^2.6.0"
keras-tuner = "^1.0.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
